const ADD_COURSE = 'ADD_COURSE';
const DELETE_COURSE = 'DELETE_COURSE';
const UPDATE_COURSE = 'UPDATE_COURSE';
const GET_COURSES = 'GET_COURSES';

export { ADD_COURSE, DELETE_COURSE, UPDATE_COURSE, GET_COURSES };
